theme: jekyll-theme-leap-day
title: Tiago Massita - Mobile Developer
description: Mobile developer, focused on native development, using Java and Kotlin for Android projects, Swift for iOS and C#, Java and Nodejs for services.
